stages:
    - build
    - test
    - deploy

build:
    stage: build
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    script:
    - eval export AWS_ACCESS_KEY_ID=${AUTOSCALE_ACCESS_KEY_ID}
    - eval export AWS_SECRET_ACCESS_KEY=${AUTOSCALE_SECRET_ACCESS_KEY}
    - eval export AWS_DEFAULT_REGION=sa-east-1
    - eval export datestr=`date +%Y%m%d-%H%M%S`
    - eval export SERVER_IMG_NAME="ami-autoscale-${datestr}"

    # Capture updated EC2 server ID
    - EC2_INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${SERVER_NAME}" --query 'Reservations[*].Instances[*].{Instance:InstanceId}' --output text)

    # Create an image from the updated EC2 server
    - IMAGE_ID=$(aws ec2 create-image --instance-id ${EC2_INSTANCE_ID} --name ${SERVER_IMG_NAME} --no-reboot --tag-specifications "ResourceType=image,Tags=[{Key=Name,Value=${SERVER_IMG_NAME}}]" --output text)

    - echo "Created Image ID ${IMAGE_ID}"

deploy:
    stage: deploy
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    script:
    - eval export LAUNCH_TEMPLATE_NAME="server-template-${datestr}"

    # Parse JSON launch template 
    - cat "${SERVER_LAUNCH_TEMPLATE_JSON}" > config.json
    - sed -i "s/ami-xxx/${IMAGE_ID}/g" config.json

    # Create launch template with the created image
    - aws ec2 create-launch-template --launch-template-name ${LAUNCH_TEMPLATE_NAME} --version-description version1 --launch-template-data file://config.json

    # Update autoscaling with the created template
    - aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${AUTOSCALE_NAME} --launch-template LaunchTemplateName=${LAUNCH_TEMPLATE_NAME},Version='1'

    - echo "AutoScaling Group = ${AUTOSCALE_NAME}"
    - echo "Template Name     = ${LAUNCH_TEMPLATE_NAME}"
    - echo "Updated with Image = ${IMAGE_ID} (Instance ID ${EC2_INSTANCE_ID})"
